name: Yarn Build Actions

on: [push]

run-name: ${{ github.actor }} 

jobs:
  yarn-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.x'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install
        shell: bash

      - name: Build
        run: yarn build
        shell: bash

      - name: Upload Docs as Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: build/docs/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
